Repository malvinh1/csic-api, pull requests merged in 2019-11, with the labels that each got.

#13 [Endpoint] Requests (Add Request, My Request, User Request)
  src/controllers/featureController.ts
  src/controllers/pageController.ts
  src/models/postModel.ts
  src/models/requestModel.ts
  src/routes/featureRoute.ts
  src/routes/pageRoute.ts
Labels: approved

#15 [HotFix] handle base64 image on editPost endpoint
  src/controllers/featureController.ts
Labels: approved

#16 [Documentation] Update image typeData
  README.md
Labels: approved

#17 [Endpoint] Follow/Unfollow user
  src/controllers/featureController.ts
  src/models/userModel.ts
  src/routes/featureRoute.ts
  src/types/index.ts
Labels: Ready for Review

#19 [FIX] Add is_followed_by_you on userProfile
  src/controllers/pageController.ts
Labels: approved

#22 [HotFix] Fix follow user
  src/controllers/featureController.ts
  src/index.ts
  src/models/userModel.ts
Labels: approved

#23 [Endpoint] Answer Request
  README.md
  src/controllers/featureController.ts
  src/controllers/pageController.ts
  src/models/requestModel.ts
  src/routes/featureRoute.ts
  src/seeder.ts
Labels: approved

#20 [Feature] Search User by its username
  src/controllers/featureController.ts
  src/models/userModel.ts
  src/routes/featureRoute.ts
Labels: approved

#21 [Documentation] Add Search Endpoint + Chats Table
  README.md
Labels: approved

#24 [Fixes] Change endpoint routes to snake-case and update documentation
  README.md
  src/routes/pageRoute.ts
Labels: Approved with minor suggestions

#25 [HotFix] Add avatar in back end response endpoint user-request and my-request
  README.md
  src/controllers/pageController.ts
Labels: approved

#27 [HotFix] Fixes endpoint my-request, user-request, answer-request, and home
  README.md
  src/controllers/featureController.ts
  src/controllers/pageController.ts
  src/models/requestModel.ts
  src/routes/featureRoute.ts
Labels: Approved with minor suggestions

#26 [Feature] Send Chat Features and Chat List Page
  README.md
  src/controllers/featureController.ts
  src/controllers/pageController.ts
  src/models/chatModel.ts
  src/routes/featureRoute.ts
  src/routes/pageRoute.ts
  src/seeder.ts
Labels: approved

#29 [Fix] delete request before deleting post
  src/db.ts
  src/models/postModel.ts
  src/seeder.ts
Labels: approved

#30 [HotFIx] Handle Request To Not Spam
  src/controllers/featureController.ts
Labels: approved

#32 [HotFix] Sorting request
  README.md
  src/controllers/pageController.ts
  src/seeder.ts
Labels: approved

#33 [HotFix] Fix unhandled logic in sign in
  src/models/userModel.ts
Labels: approved

#34 [HotFix] Fix unhandled condition
  src/models/userModel.ts
Labels: approved

#36 [Feature][Enhance] adding nearby you on search endpoint
  src/controllers/featureController.ts
  src/controllers/pageController.ts
  src/models/userModel.ts
Labels: approved

#35 [Endpoint] Following & follower user endpoint
  README.md
  src/controllers/featureController.ts
  src/routes/featureRoute.ts
Labels: approved

#37 [FIX] remove myself inside search
  src/controllers/featureController.ts
  src/models/userModel.ts
Labels: approved

#38 [Enhance] Edit following and follower list endpoint to having user_id
  src/controllers/featureController.ts
  src/db.ts
  src/routes/featureRoute.ts
Labels: approved
